codegen/src/main/resources/mustache/Java/formParams.mustache, codegen/src/main/resources/mustache/Java/headerParams.mustache, codegen/src/main/resources/mustache/Java/pathParams.mustache, codegen/src/main/resources/mustache/Java/queryParams.mustache, codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ModelsGroupApi.java, codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java, codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/PetApi.java, codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/StoreApi.java
`@BeanParams` classes require to have getter/setters or public fields, for now this is making the fields public as a workaround 
`mvn clean verify`
=> fix(beans): Public @BeanParam fields

microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/Builder.java, microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGenOperation.java, microgen-codegen/src/main/resources/mustache/Java/immutablePojo.mustache, microgen-codegen/src/main/resources/mustache/Java/model.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithComplexAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithIntegerAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithStringAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/User.java
Pojo generation with immutables library was causing issues with Json-B serialization/deserialization
`mvn clean install`
=> fix(pojos): Generate immutables pojos (manually)

microgen-archetype/pom.xml, microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/README.md, microgen-archetype/src/main/resources/archetype-resources/buildAndRun.sh, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/java/JAXRSConfiguration.java, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/microprofile-config.properties, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/openapi.yml, microgen-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/beans.xml, microgen-archetype/src/test/resources/projects/basic/archetype.properties, microgen-archetype/src/test/resources/projects/basic/goal.txt, microgen-archetype/src/test/resources/projects/basic/reference/Dockerfile, microgen-archetype/src/test/resources/projects/basic/reference/README.md, microgen-archetype/src/test/resources/projects/basic/reference/buildAndRun.sh, microgen-archetype/src/test/resources/projects/basic/reference/pom.xml, microgen-archetype/src/test/resources/projects/basic/reference/src/main/java/myservice/JAXRSConfiguration.java, microgen-archetype/src/test/resources/projects/basic/reference/src/main/resources/META-INF/microprofile-config.properties, microgen-archetype/src/test/resources/projects/basic/reference/src/main/resources/META-INF/openapi.yml, microgen-archetype/src/test/resources/projects/basic/reference/src/main/webapp/WEB-INF/beans.xml, pom.xml
=> feat: Creating MicroGen Archetype

microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGen.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java
=> fix(core): Default parameter were not being generated

microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGen.java, microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGenProperty.java, microgen-codegen/src/test/java/io/swagger/codegen/v3/generators/java/server/Java8ModelTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithComplexAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithIntegerAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/ModelWithStringAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/model/User.java
=> feat: Optimizing Optionals

microgen-bom/pom.xml, microgen-codegen/pom.xml, microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGen.java, microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/MicroGenProperty.java, microgen-codegen/src/main/java/io/swagger/codegen/v3/generators/java/ReformattingTemplateEngine.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/PetApi.java
=> fix: Format generated files

.mvn/wrapper/maven-wrapper.properties
=> chore: Maven 3.6.2

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenTemplateEngine.java, microgen-codegen/src/main/resources/META-INF/services/org.openapitools.codegen.api.TemplatingEngineAdapter, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/PetApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/PetApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/StoreApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/UserApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Category.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/InlineObject.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/ModelApiResponse.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Order.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Pet.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Tag.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/User.java
Format generated files using Google Guava
=> fix(template): Apply Google formatting to the generated files

.github/workflows/maven.yml
Enabling the maven github action
=> chore(maven): Added Github Action

.github/workflows/stale.yml
Mark stale issues and pull requests
=> chore(github): Enabling Stale check

microgen-codegen/src/main/resources/Java/formParams.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/io/swagger/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/io/swagger/server/api/PetApi.java
=> fix: Incorrect visibility in form params attribute

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/basic/reference/pom.xml, microgen-bom/pom.xml, microgen-codegen/pom.xml, microgen-samples/pom.xml
=> chore: Migrate to JakartaEE 8.0

microgen-codegen/pom.xml
=> chore(deps): Remove duplicated deps

microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/beans.xml, microgen-archetype/src/test/resources/projects/basic/eclipse-glassfish/Dockerfile, microgen-archetype/src/test/resources/projects/basic/eclipse-glassfish/pom.xml, microgen-archetype/src/test/resources/projects/basic/eclipse-glassfish/src/main/webapp/WEB-INF/beans.xml, microgen-bom/pom.xml, microgen-samples/microgen-sample-server/pom.xml
=> fix(archetype): Fix maven archetype dependencies

microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateType.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/Java8ModelTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ServerTemplateTest.java
Rename packages to remove swagger-codegen references
`mvn clean install1
=> chore: Rename package

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ServerTemplateTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> chore: Remove references to swagger

microgen-codegen/src/main/resources/Java/api.mustache, microgen-codegen/src/main/resources/Java/beanParams.mustache, microgen-codegen/src/main/resources/Java/builder.mustache, microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/PetApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/StoreApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/UserApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Category.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/InlineObject.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/ModelApiResponse.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Order.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Pet.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Tag.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/User.java
=> feat: Support for builders

microgen-codegen/src/main/resources/Java/api.mustache, microgen-codegen/src/main/resources/Java/beanParams.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java
=> fix: *Param => *Params for @BeanParams

microgen-codegen/pom.xml, microgen-codegen/src/test/resources/logback-test.xml
=> chore: Add logback-classic for tests

microgen-codegen/src/main/resources/Java/builderMethod.mustache, microgen-codegen/src/main/resources/Java/formParams.mustache, microgen-codegen/src/main/resources/Java/headerParams.mustache, microgen-codegen/src/main/resources/Java/pathParams.mustache, microgen-codegen/src/main/resources/Java/queryParams.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/PetApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/StoreApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/UserApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Category.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/InlineObject.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/ModelApiResponse.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Order.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Pet.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Tag.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/User.java
=> feat: Add builders to BeanParams

microgen-codegen/src/main/resources/Java/beanParams.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/PetApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/StoreApi.java, microgen-samples/microgen-sample-server/src/main/java/petstore/api/UserApi.java
=> feat: Add HttpHeaders and UriInfo to BeanParams

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/buildAndRun.sh, microgen-archetype/src/main/resources/archetype-resources/run-in-docker.sh, microgen-archetype/src/test/resources/projects/openliberty/buildAndRun.sh, microgen-archetype/src/test/resources/projects/openliberty/run-in-docker.sh
=> fix: Run in docker

pom.xml
=> fix: Remove parent pom

microgen-codegen/src/main/resources/Java/modelInnerEnum.mustache, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java
=> fix: Missing Jsonb serialization

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenProperty.java, microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> fix: Add missing Optional parameters

microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateType.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Category.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/InlineObject.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/ModelApiResponse.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Order.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Pet.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/Tag.java, microgen-samples/microgen-sample-server/src/main/java/petstore/models/User.java
=> fix: Add missing builder utility method

README.md
=> docs: Adding intructions in the README.md

microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> feat: Add @javax.json.bind.annotation.JsonbPropertyOrder

README.md, microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> feat: Add @JsonbPropertyOrder in docs

README.md
=> chore: Add dependencies

README.md
=> docs: Refactoring README.md

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/.dockerignore, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/filebeat/filebeat.yml, microgen-archetype/src/main/resources/archetype-resources/openliberty/server.xml, microgen-archetype/src/main/resources/archetype-resources/prometheus/prometheus.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/.dockerignore, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/filebeat/filebeat.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/openliberty/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/prometheus/prometheus.yml, microgen-codegen/src/main/java9/module-info.java
=> feat: Add docker-compose.yml

microgen-archetype/src/main/resources/archetype-resources/openliberty/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/openliberty/server.xml
=> chore: Simplify OpenLiberty server.xml

microgen-bom/pom.xml, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java9/module-info.java, microgen-codegen/src/test/resources/3_0/example.yml, pom.xml
=> chore: Clean up

microgen-bom/pom.xml, microgen-codegen/pom.xml, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenTemplateEngine.java, microgen-codegen/src/main/resources/Java/api.mustache, microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateType.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestTemplateTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupApiClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupApiClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java, pom.xml
=> feat: Generate rest clients for testing in Server

.mvn/maven.config, microgen-archetype/src/main/resources/archetype-resources/.mvn/maven.config, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/openliberty/server.xml, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/microprofile-config.properties, microgen-archetype/src/test/resources/projects/openliberty/reference/.mvn/maven.config, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/openliberty/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/microprofile-config.properties, microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Wrong OpenTracing path for the OL feature

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/microprofile-config.properties, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/microprofile-config.properties, microgen-codegen/src/main/resources/Java/api.mustache, microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> feat: Add metrics for Timers and Counters

microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/main/resources/Java/beanParams.mustache, microgen-codegen/src/main/resources/Java/beanParamsClient.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Remove @BeanParams from clients when not required

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml
=> fix(issue-169): Build issue on Archetype module

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-codegen/src/main/resources/Java/model.mustache, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/main/resources/Java/typeInfoAnnotation.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> feat: Using the immutables library

microgen-bom/pom.xml
=> chore: Immutables 2.8.0

pom.xml
=> chore: Add OSS parent POM

microgen-bom/pom.xml
=> chore(deps): Revert Bump value from 2.7.5 to 2.8.0-CriteriaRc0

README.md
=> chore: Add dependabot badge

README.md
=> chore: Maven Central Badge

microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Remove unnecessary @Dependant annotation

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml
=> chore: Update docker images

microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestExampleTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateIT.java, pom.xml
=> chore: Separate unit and integration tests

header.txt, microgen-archetype/header.txt, microgen-bom/header.txt, microgen-codegen/header.txt, microgen-codegen/src/main/java/org/openapitools/codegen/languages/Builder.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenModel.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenOperation.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenProperty.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenTemplateEngine.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/Util.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/DirectoryConstants.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/TemplateType.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestExampleTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/Java8ModelTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ServerTemplateTest.java, pom.xml
=> chore: Add License Plugin

pom.xml
=> chore: Fix JaCoCo coverage config

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenProperty.java, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/ModelTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/DataTypesTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> fix: Reuse constants as JsonbProperty values

microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ApiTestExampleTemplateIT.java, microgen-codegen/src/test/resources/3_0/petstore.yml, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/resources/PetRestClientExamples.json, microgen-codegen/src/test/resources/fixtures/petstore/src/test/resources/StoreRestClientExamples.json, microgen-codegen/src/test/resources/fixtures/petstore/src/test/resources/UserRestClientExamples.json
=> fix: Remove xml snippets from examples

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml
=> feat: Add the mongodb image to docker-compose.yml

microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> feat: Add builders to immutable classes

microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/openapi.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/openapi.yml
=> chore: Remove XML from openapi.yml

microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> feat: Add @JsonbTypeAdapter classes

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java
=> fix: Enable test files code generation

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-bom/pom.xml, pom.xml
=> fix: Update immutables library in archetype

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/test/java/PlaceholderTest.java, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/test/java/myservice/PlaceholderTest.java
=> feat: Enable Junit 5 in the archetype

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml
=> fix: Mongo port to 27017

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml
=> feat: Move docker build to a profile

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml
=> fix: Add LOG_DIR and all logging related env variables

microgen-archetype/src/main/resources/archetype-resources/src/main/java/JSONConfiguration.java, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/java/myservice/JSONConfiguration.java, microgen-codegen/src/main/resources/Java/modelTypeAdapter.mustache, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCardTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapPropertiesTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalPropertiesTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTestTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCardTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBaseTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClassTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/CategoryTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/OrderTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/PetTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/TagTypeAdapter.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/UserTypeAdapter.java
=> fix: Add Jsonb configuration and fix adapters

microgen-archetype/src/main/resources/archetype-resources/.dockerignore, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/goal.txt, microgen-archetype/src/test/resources/projects/openliberty/reference/.dockerignore, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile
=> chore: Upgrade to OpenLiberty 19.0.0.12-full-java11-openj9-ubi

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/ModelTest.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Replace operation returnType Void => javax.ws.rs.core.Response

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/resources/Java/modelPackageInfo.mustache, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateIT.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/package-info.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/package-info.java
=> chore: Being DRY using package-info.java

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/liberty/config/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/liberty/config/server.xml, microgen-codegen/src/main/java/org/openapitools/codegen/languages/Builder.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenProperty.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenTemplateEngine.java, microgen-codegen/src/main/resources/Java/builder.mustache, microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/main/resources/Java/model.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/ModelTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/DataTypesTest.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelAdapterTemplateIT.java, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateIT.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Using java beans instead of immutables library

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/java/FlywayUpdater.java, microgen-archetype/src/main/resources/archetype-resources/src/main/liberty/config/server.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/persistence.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/db/migration/V001__CREATE_PERSON.sql, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/java/myservice/FlywayUpdater.java, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/liberty/config/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/persistence.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/db/migration/V001__CREATE_PERSON.sql
=> feat: Add JPA config + MicroShed testing

microgen-archetype/pom.xml, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/goal.txt, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-bom/pom.xml, microgen-codegen/pom.xml, pom.xml
=> chore: Update to Junit 5.6 + move version numbers to parent

microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/openapi.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/openapi.yml
=> fix: use a TodoApp OpenAPI spec instead of PetStore

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/java/EntityManagerProducer.java, microgen-archetype/src/main/resources/archetype-resources/src/main/java/TodoItemEntity.java, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/apache-deltaspike.properties, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/persistence.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/db/migration/V001__CREATE_PERSON.sql, microgen-archetype/src/main/resources/archetype-resources/src/main/resources/db/migration/V001__CREATE_TODOS_TABLE.sql, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/java/myservice/EntityManagerProducer.java, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/java/myservice/TodoItemEntity.java, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/apache-deltaspike.properties, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/META-INF/persistence.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/db/migration/V001__CREATE_PERSON.sql, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/resources/db/migration/V001__CREATE_TODOS_TABLE.sql, pom.xml
=> feat: Add JPA entity and deltaspike configs

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml
=> chore: Simplify OpenLiberty plugin configuration

pom.xml
=> chore: Flyway 6.2.0

microgen-codegen/src/main/resources/Java/api.mustache, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ModelsGroupApi.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/api/ParametersGroupApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/DefaultApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/PetApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/StoreApi.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/api/UserApi.java
=> fix: Add BeanParam to the method when no params in the spec

microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml
=> fix: Wrong docker image name

microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/main/resources/archetype-resources/src/main/liberty/config/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/pom.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/liberty/config/server.xml
=> fix: Extensions and Drivers properly set

microgen-archetype/src/main/resources/archetype-resources/src/main/liberty/config/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/liberty/config/server.xml
=> fix: MicroProfile 3.3 in OpenLiberty

microgen-archetype/pom.xml
=> fix: .git* files were not generated from archetype

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/mvnw.cmd, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/mvnw.cmd
=> fix: Add prefix to docker-compose names to avoid collisions

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/Dockerfile, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/src/main/java/FlywayUpdater.java, microgen-archetype/src/main/resources/archetype-resources/src/main/liberty/config/server.xml, microgen-archetype/src/main/resources/archetype-resources/wkr.sh, microgen-archetype/src/test/resources/projects/openliberty/reference/Dockerfile, microgen-archetype/src/test/resources/projects/openliberty/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/java/myservice/FlywayUpdater.java, microgen-archetype/src/test/resources/projects/openliberty/reference/src/main/liberty/config/server.xml, microgen-archetype/src/test/resources/projects/openliberty/reference/wkr.sh
Signed-off-by: Carlos Chacin <cchacin@gmail.com>
=> chore: Minor fixes on docker-compose.yml

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/myservice/reference/pom.xml, microgen-bom/pom.xml, pom.xml
=> fix: Elevating properties / Quarkus 1.4.1

microgen-codegen/src/main/resources/Java/api_test.mustache, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ModelsGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/example/src/test/java/org/openapitools/server/api/ParametersGroupRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/DefaultRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/PetRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/StoreRestClient.java, microgen-codegen/src/test/resources/fixtures/petstore/src/test/java/org/openapitools/server/api/UserRestClient.java
=> fix: Incorrect metrics name and tags

microgen-bom/pom.xml, microgen-codegen/pom.xml, pom.xml
=> chore: Clean up pom.xml properties

microgen-archetype/src/test/resources/projects/myservice/reference/pom.xml, pom.xml
=> chore: Quarkus 1.5.0 with GraphQL support 😃

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/myservice/reference/pom.xml
=> chore: Add GraphQL extension

microgen-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, microgen-archetype/src/main/resources/archetype-resources/docker-compose.yml, microgen-archetype/src/main/resources/archetype-resources/grafana/dashboards.yml, microgen-archetype/src/main/resources/archetype-resources/grafana/datasources.yml, microgen-archetype/src/main/resources/archetype-resources/grafana/mp-dashboard.json, microgen-archetype/src/main/resources/archetype-resources/grafana/mp-fault-tolerance.json, microgen-archetype/src/main/resources/archetype-resources/postgres/servers.json, microgen-archetype/src/main/resources/archetype-resources/prometheus/prometheus.yml, microgen-archetype/src/test/resources/projects/myservice/reference/docker-compose.yml, microgen-archetype/src/test/resources/projects/myservice/reference/grafana/dashboards.yml, microgen-archetype/src/test/resources/projects/myservice/reference/grafana/datasources.yml, microgen-archetype/src/test/resources/projects/myservice/reference/grafana/mp-dashboard.json, microgen-archetype/src/test/resources/projects/myservice/reference/grafana/mp-fault-tolerance.json, microgen-archetype/src/test/resources/projects/myservice/reference/postgres/servers.json, microgen-archetype/src/test/resources/projects/myservice/reference/prometheus/prometheus.yml
=> feat: Add Grafana Microprofile Dashboards

.github/workflows/codeql-analysis.yml
=> chore: Created CodeQL workflow

README.md
=> chore: Add CodeQL Badge to README

.github/workflows/codeql-analysis.yml
=> chore: CodeQL only with Java

.github/workflows/maven.yml
=> chore: Use Github checkout action v2

.github/workflows/codeql-analysis.yml, .github/workflows/maven.yml
=> chore: Cache Maven dependencies in GitHub Actions

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/myservice/reference/pom.xml, microgen-bom/pom.xml, pom.xml
=> feat: Add MapStruct dependency

microgen-archetype/src/main/resources/archetype-resources/src/main/docker/Dockerfile.jvm, microgen-archetype/src/main/resources/archetype-resources/src/main/docker/Dockerfile.native, microgen-archetype/src/test/resources/projects/myservice/reference/src/main/docker/Dockerfile.jvm, microgen-archetype/src/test/resources/projects/myservice/reference/src/main/docker/Dockerfile.native, pom.xml
=> chore: Quarkus 1.5.1

microgen-archetype/src/main/resources/archetype-resources/pom.xml, microgen-archetype/src/test/resources/projects/myservice/reference/pom.xml
=> feat: Add the OpenAPI maven plugin

pom.xml
=> fix: Quarkus 1.5.2.Final

pom.xml
=> fix: Quarkus 1.6.0

pom.xml
=> chore: Quarkus 1.7.0.Final

microgen-codegen/src/main/resources/Java/builder.mustache, microgen-codegen/src/main/resources/Java/modelInnerEnum.mustache, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java
=> fix: Enum.fromValue

.github/workflows/maven.yml
There was an invalid argument in `.github/maven.yml` file for the maven github action
=> fix: Remove invalid argument fetch-depth

README.md, microgen-codegen/src/main/resources/Java/immutablePojo.mustache, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java
=>  feat: Added Quarkus registerForReflection annotation for POJO and ImmutablePOJO

microgen-codegen/src/main/java/org/openapitools/codegen/languages/Builder.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGen.java, microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenTemplateEngine.java, microgen-codegen/src/main/resources/Java/additionalModelTypeAnnotations.mustache, microgen-codegen/src/main/resources/Java/modelEnum.mustache, microgen-codegen/src/main/resources/Java/modelInnerEnum.mustache, microgen-codegen/src/main/resources/Java/pojo.mustache, microgen-codegen/src/test/java/org/openapitools/codegen/languages/server/ModelTemplateIT.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/AllPrimitives.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/BaseCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/EnumInteger.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/EnumNumber.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/EnumString.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithMapProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithPropertiesAndAdditionalProperties.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/ModelWithReadOnlyPropertyTest.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/PersonCard.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleBase.java, microgen-codegen/src/test/resources/fixtures/example/src/main/java/org/openapitools/server/model/SampleSubClass.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Category.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Order.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Pet.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/Tag.java, microgen-codegen/src/test/resources/fixtures/petstore/src/main/java/org/openapitools/server/model/User.java
=> fix: Models and Enums

microgen-codegen/src/main/java/org/openapitools/codegen/languages/MicroGenProperty.java
=> fix: Delegate more params from CodegenProperty
